name: Compile Examples
on: [push, pull_request]
jobs:
 build:
   runs-on: ubuntu-latest

   strategy:
     matrix:
       fqbn: [
         '"STM32:stm32:Eval:pnum=STEVAL_MKSBOX1V1,usb=CDCgen" "https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json"',
         '"STM32:stm32:Nucleo_64:pnum=NUCLEO_L476RG" "https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json"',
         '"STM32:stm32:Disco:pnum=B_L475E_IOT01A" "https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json"'
       ]

   steps:
     - uses: actions/checkout@v1
       with:
         fetch-depth: 1
     - uses: arduino/actions/libraries/compile-examples@master
       with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
         fqbn: ${{ matrix.fqbn }}
